version: "3.7"

services:
  web:
    volumes:
      - .:/var/www/html:rw

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
    networks:
      - adlinker
    restart: always
    depends_on:
      - db
